using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class RandomNameGenerator
{
    private static string[] names = new string[]
    {
        "Gervassius the Reliable",
        "Michiel the Heartbreaker",
        "Amer the Twisted",
        "LanceLanzo the Friendly",
        "Ligier the Blue",
        "Oudet the Guard",
        "Rowland the Phantom",
        "Alphonsus of the Lake",
        "Wimarc the Highborn",
        "Michiel the Heartbreaker",
        "Theodric the Giant",
        "Gervis the Cold",
        "Davi of the West",
        "Melcher of the Night",
        "Geroldin the Defender",
        "Wilkin the Jackal",
        "Nel the Messenger",
        "Hugues the Devoted",
        "Ive the Little",
        "Ingramus of the Winter",
        "Warinus the Kind",
        "Euvrouin the Bruiser",
        "Wymarc the Scar",
        "Willcock the Tough",
        "Rowan the Swift",
        "Christy of the Night",
        "Renoldus the Brown",
        "Huon the Huge",
        "Folcard the Phantom",
        "Houdoin the Creature",
        "Arnoldus the Ghost",
        "Arnaud of the Mountain",
        "Neale the Gorgeous",
        "Baret of the Dark",
        "Eudon the Demon",
        "Gylbarde the Maneater",
        "Ancelm the Warden",
        "Petur the Fearless",
        "Daue the Tracker",
        "Tedbaldus the Silence",
        "Gillet of the Fire",
        "Water the Maneater",
        "Farrimond the Weak",
        "Wally the Wolf",
        "Christofle the Powerful",
        "Thoma of the Fire",
        "Nicholaus the Conqueror",
        "Ananas the Ferocious", 
        "Odo the Horrific",
        "Hamnet the Wild",
        "Tandy the Hungry",
        "Royce the Relentless",
        "Alicia the Rude",
        "Milisent the Prodigy",
        "Ysabella the Scar",
        "Jahan of the Water",
        "Matilldis the Resolute",
        "Ysmeina the Undefeated",
        "Galienne the Scar",
        "Joneta the Hungry",
        "Mactildis the Vigilant",
        "Odolina the Valiant",
        "Ascelot the Poet",
        "Emblem the Angel",
        "Madlyn the Quick",
        "Gabriela the Bodyguard",
        "Oriold the Shepherd",
        "Masse the Honest",
        "Ezabell the Friendly",
        "Gisellee the Maneater",
        "Helisende the Talented",
        "May the Evangelist",
        "Bride the Widow",
        "Egelina of the Spring",
        "Emeline the Paladin",
        "Eleanora the Keen",
        "Kaylein the Patriot",
        "Jaquelot the Shy",
        "Madlyn the Honorable",
        "Adhelina the Honorable",
        "Bethia the Clumsy",
        "Sosanna of the Water",
        "Joane the Worthy",
        "Alienor the Powerful",
        "Muriella the Undefeated",
        "Chrestienne of the North",
        "Ibbe the Smile",
        "Miriild the Allegiant",
        "Maudeleyn the Protector",
        "Imeyna of the Mountain",
        "Moude the Kind",
        "Emelot of the Mountain",
        "Cristina the Clever",
        "Ysabella the Scar",
        "Bathsheba the Little",
        "Brigit the Heartbreaker",
        "Rikild the Tiny",
        "Hyssmaye the Relentless",
        "Herleva the Gentlewoman",
        "Tilla the Ghost",
        "Aelizia the Dragonslayer", 
        "Bob the Old"
    }; 
    
    public static string getRandomName()
    {
        int a = (int)Random.Range(0f, names.Length);
        int b = (int)Random.Range(0f, names.Length);
        string toRemove = System.Text.RegularExpressions.Regex.Replace(names[b].Split()[0], @"[^0-9a-zA-Z\ ]+", "");
        int c = toRemove.Length+1;
        string name = System.Text.RegularExpressions.Regex.Replace(names[a].Split()[0], @"[^0-9a-zA-Z\ ]+", "") + " "
            + names[b].Remove(0, c); 
        return name; 
    }
}
